name: projgen
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/osobotu/projgen

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  build_cli_annotations: ^2.1.0
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  build_cli: ^2.0.0
  build_runner: ^2.0.6
  lints: ^2.0.0
  test: ^1.16.0
